version: "3.7"
services:
  http-api:
    image: gcr.io/radicle-services/http-api:${RADICLE_IMAGE_TAG:-latest}
    entrypoint: /usr/local/bin/radicle-http-api --listen 0.0.0.0:8777 --root /app/radicle --passphrase seed
    build:
      dockerfile: ./http-api/Dockerfile
      context: .
    volumes:
      - /var/opt/radicle:/app/radicle
    environment:
      RUST_LOG: info
      RAD_HOME: /app/radicle
    init: true
    container_name: http-api
    restart: unless-stopped
    networks:
      - radicle-services
    depends_on:
      - git-server
  git-server:
    image: gcr.io/radicle-services/git-server:${RADICLE_IMAGE_TAG:-latest}
    entrypoint: /usr/local/bin/radicle-git-server.sh $RADICLE_GIT_SERVER_OPTS --root /app/radicle --passphrase seed
    build:
      dockerfile: ./git-server/Dockerfile
      context: .
    volumes:
      - /var/opt/radicle:/app/radicle
    environment:
      RUST_LOG: hyper=warn,debug
      RAD_HOME: /app/radicle
    init: true
    container_name: git-server
    restart: unless-stopped
    networks:
      - radicle-services
    deploy:
      resources:
        limits:
          memory: 6gb
  caddy:
    image: caddy:2.4.5
    ports:
      - 80:80
      - 443:443
      - 8777:8777
      - 8086:8086
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      RADICLE_DOMAIN: $RADICLE_DOMAIN
    container_name: caddy
    restart: unless-stopped
    networks:
      - radicle-services

networks:
  radicle-services:
    name: radicle-services
