name: Build and push container images

on:
  push:
    branches:
      - deploy/*

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push http-api
        id: http_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: http-api/Dockerfile
          push: true
          tags: gcr.io/radicle-services/http-api:latest,gcr.io/radicle-services/http-api:${{ github.sha }}
          cache-from: type=registry,ref=gcr.io/radicle-services/http-api:latest
          cache-to: type=inline
      - name: Build and push git-server
        id: git_server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: git-server/Dockerfile
          push: true
          tags: gcr.io/radicle-services/git-server:latest,gcr.io/radicle-services/git-server:${{ github.sha }}
          cache-from: type=registry,ref=gcr.io/radicle-services/git-server:latest
          cache-to: type=inline
